name: Crypto App
 
on:
  push:
    branches: [ master ]
 
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Deploy Crypto App
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            pm2 stop all
            cd ~/binance-dir/binance-bot/ # navigate into the folder
            git pull
            npm install # install dependencies 
            # pm2 start server.js # start as a background service.
            # pm2 start "node ace run:scheduler" --name adonis-scheduler
            pm2 start all --watch
